name: 'Build and Push'
description: 'Build and push to GCR'
inputs:
  image-name:
    description: 'Image name'
    required: true
  gcp-project-id:
    description: 'GCP project ID'
    required: true
outputs:
  image:
    description: 'Image address'
    value: ${{ steps.image-metadata.outputs.image }}
  image-tag:
    description: 'Image tag'
    value: ${{ steps.image-metadata.outputs.tag }}
runs:
  using: 'composite'
  steps:
    - id: image-metadata
      name: Extract image metadata
      run: |-
        REF_NAME=$(echo ${GITHUB_REF#refs/*/} | sed -e 's/^v//' | tr -c '[[:alnum:]]._-' '_')
        echo "inputs.gcp-project-id=${{ inputs.gcp-project-id }}"
        echo "inputs.image-name=${{ inputs.image-name }}"
        echo "REF_NAME=${ REF_NAME }"
        echo "::set-output name=tag::$TAG"
        echo "::set-output name=image::$(echo "gcr.io/${{ inputs.gcp-project-id }}/${{ inputs.image-name }}:${REF_NAME}")"
      shell: bash

    # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
      shell: bash

    - name: Build image
      run: |-
        docker build \
          --tag "${{ steps.image-metadata.outputs.image }}" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
      shell: bash

    - name: Publish images to GCR
      run: |-
        docker push "${{ steps.image-metadata.outputs.image }}"
      shell: bash
