name: 'Build and Push'
description: 'Build and push to GCR'
inputs:
  image-name:
    description: 'Image name'
    required: true
  gcp-project-id:
    description: 'GCP project ID'
    required: true
  gcp-service-account-key:
    description: 'GCP service account key'
    required: false
  dockerfile:
    description: 'Name of the Dockerfile to use'
    default: './Dockerfile'
    required: false
  build-optons:
    description: 'Additional options to pass to docker build command'
    default: ''
    required: false
outputs:
  image:
    description: 'Image address'
    value: ${{ steps.image-metadata.outputs.image }}
  image-tag:
    description: 'Image tag'
    value: ${{ steps.image-metadata.outputs.tag }}
runs:
  using: 'composite'
  steps:
    - id: image-metadata
      name: Extract image metadata
      run: |-
        REF_NAME=$(echo ${GITHUB_REF#refs/*/} | sed -e 's/^v//')
        TAG=$(printf ${REF_NAME} | tr -c '[[:alnum:]]._-' '_')
        if [[ "${REF_NAME}" == "main" || "${REF_NAME}" == "master" ]]; then TAG=latest; fi
        echo "inputs.gcp-project-id=${{ inputs.gcp-project-id }}"
        echo "inputs.image-name=${{ inputs.image-name }}"
        echo "REF_NAME=$REF_NAME"
        echo "TAG=$TAG"
        echo "::set-output name=tag::$TAG"
        echo "::set-output name=image::$(echo "gcr.io/${{ inputs.gcp-project-id }}/${{ inputs.image-name }}:${TAG}")"
      shell: bash

    # Configure Docker access to the Container Registry
    - run: |-
        if [[ -z "$GCP_SERVICE_ACCOUNT_KEY" ]]; then \
          gcloud --quiet auth configure-docker; \
        else \
          docker login -u _json_key -p "$GCP_SERVICE_ACCOUNT_KEY" https://gcr.io; \
        fi
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ inputs.gcp-service-account-key }}
      shell: bash

    - name: Build image
      run: |-
        docker build \
          --tag "${{ steps.image-metadata.outputs.image }}" \
          --file "${{ inputs.dockerfile }}" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ${{ inputs.build-options }} \
          .
      shell: bash

    - name: Publish images to GCR
      run: |-
        docker push "${{ steps.image-metadata.outputs.image }}"
      shell: bash
