name: Test action
on:
  push:
jobs:
  should-set-output-image:
    name: Should set output image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: 'dimw/mockbin-action@main'
        with:
          commands: |
            docker

      - name: Act
        uses: './'
        with:
          image-name: 'example-app'
          image-tag: test
          gcp-service-account-key: |-
            {
              "type": "service_account",
              "project_id": "my-project-1234",
              "client_email": "foo@example.com"
            }

      - uses: 'dimw/mockbin-action@main'
        with:
          commands: docker
          assert-args: |
            ["login", "--username", "_json_key", "--password-stdin", "gcr.io"]
            ["build", "--tag", "gcr.io/my-project-1234/example-app:test", "--file", "./Dockerfile", "."]
            ["push", "gcr.io/my-project-1234/example-app:test"]
